################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content"
weight = 1
[en.params]
########### footer content ##########
footer_menu_left = "About"
footer_menu_middle = "Resources"
footer_menu_right = "Links"
footer_content = "Salahaddin University Research Center - A leading hub for scientific innovation, research excellence, and collaborative discovery in Kurdistan."


