# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Events"
url = "/events"
weight = 2

[[main]]
name = "Projects"
url = "/projects"
weight = 3

[[main]]
name = "Publications"
url = "/publications"
weight = 4

[[main]]
name = "Units"
url = "/units"
weight = 5

[[main]]
name = "Labs"
url = "/labs"
weight = 6

# footer menu left
[[footer_left]]
name = "About Us"
url = "/about"

[[footer_left]]
name = "Research Units"
url = "/units"

[[footer_left]]
name = "Projects"
url = "/projects"

[[footer_left]]
name = "Publications"
url = "/publications"

# footer menu middle
[[footer_middle]]
name = "Labs"
url = "/labs"

[[footer_middle]]
name = "Events"
url = "/events"

[[footer_middle]]
name = "Staff & Researchers"
url = "/staff"

[[footer_middle]]
name = "Contact Us"
url = "/contact"

# footer menu right
[[footer_right]]
name = "Testimonials"
url = "/testimonials"

[[footer_right]]
name = "Units"
url = "/units"

[[footer_right]]
name = "University Website"
url = "https://su.edu.krd"